<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ptWLnt7' shared service.

return $this->privates['service_locator.ptWLnt7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('taskRepository' => function (): ?\App\Repository\TaskRepository {
    return ($this->privates['App\Repository\TaskRepository'] ?? $this->load('getTaskRepositoryService.php'));
}));
