<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsmIC3F\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsmIC3F/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDsmIC3F.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDsmIC3F\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDsmIC3F\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DsmIC3F',
    'container.build_id' => '81941f6b',
    'container.build_time' => 1523552352,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsmIC3F');
